// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8Cu_E-s9Q_xo-nx5FWDrJKyeuTP4B8E',
    appId: '1:854121097016:web:e0b31f50fb351b0e2183cd',
    messagingSenderId: '854121097016',
    projectId: 'job-and-freelancing',
    authDomain: 'job-and-freelancing.firebaseapp.com',
    storageBucket: 'job-and-freelancing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1eDQl0tHqlyJdNyh-X8mwI-DpT5D-mWA',
    appId: '1:854121097016:android:2f478a9c17cacbb72183cd',
    messagingSenderId: '854121097016',
    projectId: 'job-and-freelancing',
    storageBucket: 'job-and-freelancing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudM6f_R7r5uX31jtd4n1mBH_q66vx0l8',
    appId: '1:854121097016:ios:059fd4b90c17c93b2183cd',
    messagingSenderId: '854121097016',
    projectId: 'job-and-freelancing',
    storageBucket: 'job-and-freelancing.appspot.com',
    iosBundleId: 'com.example.empco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudM6f_R7r5uX31jtd4n1mBH_q66vx0l8',
    appId: '1:854121097016:ios:059fd4b90c17c93b2183cd',
    messagingSenderId: '854121097016',
    projectId: 'job-and-freelancing',
    storageBucket: 'job-and-freelancing.appspot.com',
    iosBundleId: 'com.example.empco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8Cu_E-s9Q_xo-nx5FWDrJKyeuTP4B8E',
    appId: '1:854121097016:web:a4addbd55351461f2183cd',
    messagingSenderId: '854121097016',
    projectId: 'job-and-freelancing',
    authDomain: 'job-and-freelancing.firebaseapp.com',
    storageBucket: 'job-and-freelancing.appspot.com',
  );

}